# Generated by Django 3.2.4 on 2021-06-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('f_l_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stimulation', models.TextField(blank=True, max_length=255, null=True)),
                ('by_whom', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hodim',
        ),
    ]
