# Generated by Django 3.2.4 on 2021-06-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210625_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='by_whom',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='data',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='f_l_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='stimulation',
        ),
        migrations.AddField(
            model_name='employees',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Ragbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('fulname', models.CharField(max_length=200)),
                ('aboutstimulation', models.TextField(blank=True, max_length=255, null=True)),
                ('confirmation', models.BooleanField(default=True)),
                ('by_whom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employees')),
            ],
        ),
    ]
