# Generated by Django 3.2.4 on 2021-06-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210625_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragbat',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
