# Generated by Django 3.2.4 on 2021-06-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('To_do', models.TextField()),
                ('By_whom', models.CharField(blank=True, max_length=250, null=True)),
                ('Time_Lider', models.DateField(auto_now=True)),
                ('Fine', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Signatur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.BooleanField(default=False)),
            ],
        ),
    ]
