# Generated by Django 3.2.4 on 2021-06-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jarimali_daftar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signatur',
        ),
        migrations.RenameField(
            model_name='fines',
            old_name='By_whom',
            new_name='by_whom',
        ),
        migrations.RenameField(
            model_name='fines',
            old_name='Fine',
            new_name='fine',
        ),
        migrations.RenameField(
            model_name='fines',
            old_name='Time_Lider',
            new_name='time_Lider',
        ),
        migrations.RenameField(
            model_name='fines',
            old_name='To_do',
            new_name='to_do',
        ),
        migrations.AddField(
            model_name='fines',
            name='signature',
            field=models.BooleanField(default=False),
        ),
    ]
